### ISSUE TITLE
Usuwanie mapy

### ISSUE THREAD

**Issue by lszelest** [bystrzakk/AutomaticCarsGame#13]
1) całkowite, jeżeli nie została nigdy użyta
2) deleted=true jeżeli ktoś już na niej grał

Nie można zagrać na usuniętej lub oznaczonej deleted=true mapie

**Comment by apaczuski00** [comment]
to jak tak nie potrzebne jest pole "used" ? @lszelest

**Comment by apaczuski00** [comment]
czyli albo oba pola beda na false albo oba na true?

**Comment by lszelest** [comment]
tak
